.github/ct.yaml
.github/workflows/test.yml
.gitignore
charts/flipt/Chart.yaml
charts/flipt/templates/_helpers.tpl
charts/flipt/templates/deployment.yaml
charts/flipt/templates/pvc.yaml
charts/flipt/values.yaml
ct.yaml

Should fix https://github.com/flipt-io/flipt/issues/963

support persistent volumes/pvc

---

charts/flipt/Chart.yaml

Bump chart for [latest release](https://github.com/flipt-io/flipt/releases/tag/v1.13.0) of Flipt

Bump for v0.12

---

charts/flipt/templates/deployment.yaml
charts/flipt/values.yaml

Hey there!
Thanks for this Helm chart, it works great! While `helm template`ing and trying to run Flipt as non-root I came across a couple issues related to file system permissions.
I'm using CockroachDB and this requires user certificates to successfully connect. I usually just put them into a `Secret` and mount them, then configure the DSN accordingly.
For reference, this is my DSN:
```
cockroach://production_flipt@cockroachdb-public.cockroachdb-system.svc.cluster.local:26257/production_flipt?sslmode=verify-full&sslcert=/etc/certificates/cockroachdb/tls.crt&sslkey=/etc/certificates/cockroachdb/tls.key&sslrootcert=/etc/certificates/cockroachdb/ca.crt
```
[I know, that's quite a lot of options for SSL 😅]
Additionally, I always want to run everything as non-root and luckily, your …

Fix file permissions when using security context + CockroachDB client certificates

---

.github/workflows/update.yml

Fixes: FLI-102
This is a workflow which when triggered bumps the Flipt `appVersion` in the chart YAML to the latest release version.
It also does a `MINOR` bump for the helm chart itself.

feat: add workflow to auto-update chart to latest Flipt release

---

lintconf.yaml

Re: #39 
Overrides the default `lintconf.yaml` for the `ct lint` step, allowing `1` space between content and comments

chore: add lintconf with overriden comment lint config

---

charts/flipt/Chart.yaml
charts/flipt/templates/servicemonitor.yaml
charts/flipt/values.yaml

This resource allows the Prometheus Operator to pick this service up for metrics scraping.
Maybe `{{- if and ($.Capabilities.APIVersions.Has "monitoring.coreos.com/v1/ServiceMonitor") .enabled }}` can be included to only install when the CRD is included? Some charts like for example Loki does this, but others like ArgoCD don't. So... idk 🤷

feat: add servicemonitor resource for Prometheus Operator scraping

---

charts/flipt/Chart.yaml
charts/flipt/values.yaml

Made a mistake in my previous PR, the port should not be a number but the name of the http port in the svc `http`.
So apologies about the extra PR, but better this than to leave something broken right.

fix: svc monitor port

---

charts/flipt/Chart.yaml
charts/flipt/templates/_helpers.tpl
charts/flipt/templates/hpa.yaml

Since k8s v1.25 hpa/v2beta1 is no longer available. This PR updates it to v2, which has been available since k8s v1.23 [docs](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#horizontalpodautoscaler-v125)
Target syntax has been changed a bit as well. [docs](https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale-walkthrough/#autoscaling-on-multiple-metrics-and-custom-metrics)
Also included a small fix to get the `podAnnotations` to work again.

perf: update hpa version

---

.github/workflows/update.yml

This should fix our issue where CI does not run on the generated PRs.

fix(github): use generated token instead of default

---

charts/flipt/Chart.yaml
charts/flipt/templates/_helpers.tpl
charts/flipt/templates/configmap.yaml
charts/flipt/templates/migration_job.yaml
charts/flipt/values.yaml

This will run before an install or upgrade. It will block the deployment from going out if the migration fails. Helm will also clean up the job after it finishes running.
https://helm.sh/docs/topics/charts_hooks/#the-available-hooks
Fixes: https://github.com/flipt-io/helm-charts/issues/68. 
The request was for an init container but those will run any time a pod comes up, which could be fairly often if the HPA are flapping and has the potential to lock up the database if multiple migrations are run at the same time. Using a hook ensure that only 1 of these container will be running at any given time and only on initial deployment.

Add Migration job in Helm Hook

---

charts/flipt/Chart.yaml
charts/flipt/templates/tests/test-connection.yaml
charts/flipt/values.yaml

I don't like relying on latest images since they can change under you unexpectedly. This give the option to pin to a version of busybox so each time you deploy you know which version you'll get

Allow tagging of the test container busybox

---

.github/workflows/update.yml
.gitignore
README.md
scripts/bumpVersion/main.js
scripts/bumpVersion/package-lock.json
scripts/bumpVersion/package.json

Fixes: #85
Try to better automate keeping `verison` and `appVersion` in sync strategy wise.
This should:
- set `appVersion` to latest Flipt tag
- set `version` according to the semver change to `appVersion`:
- if `minor` bump, bump `version` minor
- if `patch` bump, bump `version` patch
This is inline with our versioning strategy #85

chore: try to better automate bump chart strategy

---

README.md
charts/flipt/Chart.yaml
charts/flipt/values.yaml

use our custom docker registry (proxy) so we can change from Docker Hub to ghcr.io if need be

chore: update Docker registry

---

charts/flipt/Chart.yaml
charts/flipt/templates/deployment.yaml
charts/flipt/values.yaml

Add support for extra volumes. This can be useful for mounting files from k8s secrets and referencing them from the flipt config (e.g. Git SSH key files).

feat: add support for extra volumes

---

charts/flipt/Chart.yaml
charts/flipt/templates/configmap_ssh.yaml
charts/flipt/templates/deployment.yaml
charts/flipt/values.yaml

Supports https://github.com/flipt-io/flipt/issues/2386
This adds a new configuration `ssh.knownHosts` which allows the user to override the known hosts configuration for Flipt. The user should put the entire contents of the known hosts file they want in this field.
Configuring a non-empty string for known hosts creates:
- configmap
- volume
- volumeMount
- env var entry
cc @jalaziz

feat(ssh): add field for configuring ssh known hosts

---

charts/flipt/Chart.yaml
charts/flipt/templates/deployment.yaml

When `ssh.knownHosts` is provided, the path set in the `SSH_KNOWN_HOSTS` environment variable did not match the file mounted from the config map.

fix(chart): Fix SSH_KNOWN_HOSTS env var file path

---

charts/flipt/Chart.yaml
charts/flipt/templates/deployment.yaml
charts/flipt/values.yaml

Fixes #134 
Adds support for `envFrom` to `flipt` configuration section in Values.yml
cc @nopasutsamp

feat(charts/flipt): add support for envFrom

---

charts/flipt/Chart.yaml
charts/flipt/values.yaml

This change enabled deploying this helm chart, out-of-the-box, into a namespace
that has restricted PSS (pod security standards -- the replacement to PSP) enforcement enabled.
Read more about PSS here: https://kubernetes.io/docs/concepts/security/pod-security-standards/

feat: Include the seccompProfile in default securityContext

---

charts/flipt/Chart.yaml
charts/flipt/templates/migration_job.yaml

Adds `envFrom` to the migration job spec.

fix(charts/flipt): add envFrom to migration job

---

charts/flipt/Chart.yaml
charts/flipt/templates/deployment.yaml
charts/flipt/values.yaml

Additional pod labels are often needed, for instance, when configuring Istio injection.

feat: allow specifying additional pod labels

---

charts/flipt/Chart.yaml
charts/flipt/templates/servicemonitor.yaml

Additional labels that can be used so ServiceMonitor resource can be discovered by Prometheus
`.Values.metrics.serviceMonitor.labels` is already defined in `values.yaml` but was not used

feat: include servicemonitor additional labels to template

---

charts/flipt/Chart.yaml
charts/flipt/templates/deployment.yaml
charts/flipt/values.yaml

This allows the configurer to provide other arguments to the `flipt` command (e.g. `--force-migrate`).

feat(charts/flipt): add support for custom args

---

charts/flipt/Chart.yaml
charts/flipt/templates/pdb.yaml

Switch to `flipt.selectorLabels` in the pdb as all requirements from `matchLabels` are ANDed together ([docs](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#resources-that-support-set-based-requirements)). If `flipt.labels` has other labels configured, the pdb will never match.
https://github.com/flipt-io/helm-charts/blob/0ac3dd2cb637e80d213eab7b126bc24ff2feb908/charts/flipt/templates/deployment.yaml#L21-L25

fix: use selectorLabels in pdb

---

charts/flipt/Chart.yaml
charts/flipt/templates/deployment.yaml
charts/flipt/values.yaml

Different environments and different configuration may have different expectations for liveness and readiness.
We have experienced that the initial startup using declarative 'git' backend can take 30s or more on some occasions, which means that the default liveness probe would kill the container before it could complete.
By exposing these for users to override and configure, alternative initialDelay, periodSeconds, and thresholds are able to be tweaked and refined to support the user's specific expectations.
By default, the same probes that were previously hardcoded are configured in the defaulti values.yaml.

Expose liveness and readiness probe configuration in values settings

---

charts/flipt/Chart.yaml
charts/flipt/templates/migration_job.yaml

fixes: https://github.com/flipt-io/flipt/issues/3616
Hey, when using --set migrations.enabled=true, and using --set persistence.enabled=true with SQLite, migrations fail because the persistent volume is not mounted into the pod of the migration job.
For testing and eval systems, using the SQLite is good enough and so it would be good to also be able to run the migrations automatically on them.
I created a copy of the migration job pod with the PVC mounted and it worked well!

fix: mount persistence PVC into migration

---

charts/flipt/Chart.yaml

In #193 the latest app version was changed to previous one.

fix: use the latest version of Flipt

---

charts/flipt/Chart.yaml
charts/flipt/templates/servicemonitor.yaml
charts/flipt/values.yaml

Discussion: https://community.flipt.io/t/prometheus-as-source-for-analytics/58/11
Prometheus config defaults to `false`, so this PR would not change any behaviour.

feat: expose honorLabels key in ServiceMonitor

---

README.md
charts/flipt/Chart.yaml
charts/flipt/README.md
charts/flipt/templates/ingress.yaml
charts/flipt/values.yaml

Fixes issue described in https://community.flipt.io/t/helm-nil-pointer-evaluating-interface-servicename/90/2

feat: add default backend for ingress

---

charts/flipt/Chart.yaml
charts/flipt/templates/deployment.yaml
charts/flipt/values.yaml

- add image.Comand value to support running flipt v2
example
```yaml
image:
tag: "v2-beta"
command: [] # uses command from the original Dockerfile
```

feat: add image.command value
